resilience4j:
  circuitbreaker:
    instances:
      customer-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      customer-service:
        waitDuration: 10s
        maxAttempts: 5
  ratelimiter:
    instances:
      customer-service:
        registerHealthIndicator: true
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s

management:
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreaker, retry, ratelimiter, metrics
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true

  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

spring:
  application:
    name: customer-service
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true